version: '3.8'

services:
  web:
    build: .
    command: bash -c 'uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
  mongodb:
    image: mongo
    ports:
      - 27010:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mayssa
      - MONGO_INITDB_ROOT_PASSWORD=mayssa
#    volumes:
#      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mayssa
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mayssa
      - ME_CONFIG_MONGODB_SERVER=mongodb
  apache-tika:
    image: apache/tika
    ports:
      - 9998:9998
volumes:
  postgres_data: